cm_mounts = ['132117','129552','132118','132119']
int_specs = set(['elemental-shaman','balance-druid','restoration-druid','shadow-priest','mage',
                 'warlock','holy-priest','discipline-priest','shadow-priest','mistweaver-monk',
                 'restoration-shaman','holy-paladin'])
spi_specs = set(['holy-priest','discipline-priest','shadow-priest','balance-druid','restoration-druid',
                 'holy-paladin','mistweaver-monk','elemental-shaman','restoration-shaman'])
str_specs = set(['protection-warrior','blood-dk','protection-paladin','retribution-paladin','frost-dk',
                 'unholy-dk','fury-warrior','arms-warrior'])
agi_specs = set(['hunter','guardian-druid','feral-druid','rogue','brewmaster-monk','windwalker-monk',
                 'enhancement-shaman'])
tank_specs = set(['protection-warrior','blood-dk','protection-paladin','brewmaster-monk',
                  'guardian-druid'])
healer_specs = set(['holy-priest','discipline-priest','restoration-druid','mistweaver-monk',
                    'restoration-shaman','holy-paladin'])
dps_specs = set(['hunter','guardian-druid','feral-druid','rogue','brewmaster-monk','windwalker-monk',
                 'enhancement-shaman','retribution-paladin','frost-dk','unholy-dk','fury-warrior',
                 'arms-warrior','mage','warlock','shadow-priest','balance-druid','elemental-shaman'])
armorMap = {'Cloth':['priest','mage','warlock'],
            'Leather':['druid','monk','rogue'],
            'Mail':['hunter','shaman'],
            'Plate':['warrior','death knight','paladin']}                        
weapon_map = {'Fist Weapon':set(['balance-druid',
                                 'restoration-druid',
                                 'mistweaver-monk',
                                 'brewmaster-monk',
                                 'windwalker-monk',
                                 'rogue',
                                 'enhancement-shaman',
                                 'elemental-shaman',
                                 'restoration-shaman',
                                 'fury-warrior',
                                 'protection-warrior']),
              'One-Hand Axe':set(['frost-dk',
                                  'mistweaver-monk',
                                  'brewmaster-monk',
                                  'windwalker-monk',
                                  'protection-paladin',
                                  'rogue',
                                  'enhancement-shaman',
                                  'elemental-shaman',
                                  'restoration-shaman',
                                  'fury-warrior',
                                  'protection-warrior']),
              'Two-Hand Axe':set(['blood-dk',
                                  'frost-dk',
                                  'unholy-dk',
                                  'retribution-paladin',
                                  'arms-warrior',
                                  'fury-warrior']),
              'Dagger':set(['restoration-druid',
                            'balance-druid',
                            'mage',
                            'warlock',
                            'shadow-priest',
                            'holy-priest',
                            'discipline-priest',
                            'rogue',
                            'elemental-shaman',
                            'enhancement-shaman',
                            'restoration-shaman',
                            'fury-warrior',
                            'protection-warrior']),
              'One-Hand Mace':set(['frost-dk',
                                   'restoration-druid',
                                   'balance-druid',
                                   'brewmaster-monk',
                                   'windwalker-monk',
                                   'mistweaving-monk',
                                   'protection-paladin',
                                   'holy-paladin',
                                   'holy-priest',
                                   'discipline-priest',
                                   'rogue',
                                   'elemental-shaman',
                                   'enhancement-shaman',
                                   'restoration-shaman',
                                   'fury-warrior',
                                   'protection-warrior']),
              'Two-Hand Mace':set(['blood-dk',
                                  'frost-dk',
                                  'unholy-dk',
                                  'retribution-paladin',
                                  'feral-druid',
                                  'guardian-druid',
                                  'arms-warrior',
                                  'fury-warrior']),
              'One-Hand Sword':set(['frost-dk',
                                    'mage',
                                    'warlock',
                                    'brewmaster-monk',
                                    'windwalker-monk',
                                    'mistweaving-monk',
                                    'holy-paladin',
                                    'protection-paladin',
                                    'rogue',
                                    'fury-warrior',
                                    'protection-warrior']),
              'Two-Hand Sword':set(['blood-dk',
                                    'frost-dk',
                                    'unholy-dk',
                                    'retribution-paladin',
                                    'arms-warrior',
                                    'fury-warrior']),
              'Staff':set(['balance-druid',
                           'feral-druid',
                           'guardian-druid',
                           'restoration-druid',
                           'mage',
                           'warlock',
                           'mistweaver-monk',
                           'brewmaster-monk',
                           'windwalker-monk',
                           'holy-priest',
                           'discipline-priest',
                           'shadow-priest',
                           'elemental-shaman',
                           'restoration-shaman',
                           'arms-warrior',
                           'fury-warrior']),
              'Polearm':set(['blood-dk',
                             'unholy-dk',
                             'frost-dk',
                             'feral-druid',
                             'balance-druid',
                             'guardian-druid',
                             'restoration-druid',
                             'mistweaver-monk',
                             'brewmaster-monk',
                             'windwalker-monk',
                             'retribution-paladin',
                             'fury-warrior',
                             'arms-warrior']),
              'Bow':set(['hunter']),
              'Crossbow':set(['hunter']),
              'Gun':set(['hunter']),
              'Wand':set(['mage',
                          'warlock',
                          'holy-priest',
                          'discipline-priest',
                          'shadow-priest'])}

breedmap = {'3' : {'health':0.5,'power':0.5,'speed':0.5},
            '13': {'health':0.5,'power':0.5,'speed':0.5},
            '4' : {'health':0,  'power':2,  'speed':0},
            '14': {'health':0,  'power':2,  'speed':0},
            '5' : {'health':0,  'power':0,  'speed':2},
            '15': {'health':0,  'power':0,  'speed':2},
            '6' : {'health':2,  'power':0,  'speed':0},
            '16': {'health':2,  'power':0,  'speed':0},
            '7' : {'health':0.9,'power':0.9,'speed':0},
            '17': {'health':0.9,'power':0.9,'speed':0},
            '8' : {'health':0,  'power':0.9,'speed':0.9},
            '18': {'health':0,  'power':0.9,'speed':0.9},
            '9' : {'health':0.9,'power':0,  'speed':0.9},
            '19': {'health':0.9,'power':0,  'speed':0.9},
            '10': {'health':0.4,'power':0.9,'speed':0.4},
            '20': {'health':0.4,'power':0.9,'speed':0.4},
            '11': {'health':0.4,'power':0.4,'speed':0.9},
            '21': {'health':0.4,'power':0.4,'speed':0.9},
            '12': {'health':0.9,'power':0.4,'speed':0.4},
            '22': {'health':0.9,'power':0.4,'speed':0.4} }