weaponSubClass = {'0':'One-Hand Axe',
                  '1':'Two-Hand Axe',
                  '2':'Bow',
                  '3':'Gun',
                  '4':'One-Hand Mace',
                  '5':'Two-Hand Mace',
                  '6':'Polearm',
                  '7':'One-Hand Sword',
                  '8':'Two-Hand Sword',
                  '9':'Obsolete',
                  '10':'Staff',
                  '11':'Exotic',
                  '12':'Exotic',
                  '13':'Fist Weapon',
                  '14':'Miscellaneous',
                  '15':'Dagger',
                  '16':'Thrown',
                  '17':'Spear',
                  '18':'Crossbow',
                  '19':'Wand',
                  '20':'Fishing Pole'}
                  
armorSubClass = ['Miscellaneous','Cloth','Leather','Mail','Plate','Cosmetic','Shield']

statmap = {'3':'agility',
           '36':'haste',
           '31':'hit',
           '7':'stamina',
           '49':'mastery',
           '37':'expertise',
           '5':'intellect',
           '6':'spirit',
           '32':'crit',
           '4':'strength',
           '13':'dodge',
           '14':'parry'}

inventoryType = {'1':'Head',
                 '2':'Neck',
                 '3':'Shoulders',
                 '4':'Shirt',
                 '5':'Chest',
                 '6':'Waist',
                 '7':'Legs',
                 '8':'Feet',
                 '9':'Wrists',
                 '10':'Hands',
                 '11':'Ring',
                 '12':'Trinket',
                 '13':'Weapon',
                 '14':'Off-Hand',
                 '15':'Weapon',
                 '16':'Back',
                 '17':'Weapon',
                 '18':'Bag',
                 '19':'Tabard',
                 '20':'Chest',
                 '21':'Weapon',
                 '22':'Off-Hand',
                 '23':'Off-Hand',
                 '24':'Ammo',
                 '25':'Thrown',
                 '26':'Weapon',
                 '27':'Relic'}

allowableClasses = ['None','Warrior','Paladin','Hunter','Rogue','Priest','Death Knight','Shaman','Mage','Warlock','Monk','Druid']