from five import grok
from plone.directives import form
from Products.Five.browser import BrowserView
from Products.CMFCore.utils import getToolByName
from Products.CMFPlone import PloneMessageFactory as _
from Products.Five.browser.pagetemplatefile import ZopeTwoPageTemplateFile, ViewPageTemplateFile
from Products.statusmessages.interfaces import IStatusMessage
from z3c.form import button
from urllib import urlopen
import json

gnabb = [
{'name':'Cursed Swabby Helmet',
  'source':'Sunken Treasure',
  'rare':True,
  'pet':False,
  'location':'Shipwreck south of Old Pi\'jiu - weekly',
  'alternative':'',
  'id':104038},
{'name':'Warped Warning Sign',
  'source':'Ordon Oathguard',
  'rare':False,
  'pet':False,
  'location':'Firewalker Ruins',
  'alternative':'',
  'id':104330},
{'name':'Giant Purse of Timeless Coins',
  'source':'Karkanos',
  'rare':True,
  'pet':False,
  'location':'Fishing dock on the south, central coast.',
  'alternative':'',
  'id':104035},
{'name':'Crystal of Insanity',
  'source':'Eerie Crystal',
  'rare':False,
  'pet':False,
  'location':'Cavern of Lost Spirits. These are the purple containers throughout the cave',
  'alternative':'Sulik\'shor - rare in Valley of the Four Winds',
  'id':86569},
{'name':'Battle Horn',
  'source':'Ordon Candlekeeper',
  'rare':False,
  'pet':False,
  'location':'Firewalker Ruins',
  'alternative':'Blackhoof - rare in Valley of the Four Winds',
  'id':86565},
{'name':'Elixir of Ancient Knowledge',
  'source':'Archiereus of Flame',
  'rare':True,
  'pet':False,
  'location':'Ordon Sanctuary (cloak area), also summonable north of the court with a vendor item',
  'alternative':'Krol the Blade, rare in Dread Wastes along the wall',
  'id':86574},
{'name':'Forager\'s Gloves',
  'source':'Burning Berserkers',
  'rare':False,
  'pet':False,
  'location':'The Blazing Way',
  'alternative':'Korda Torros, rare in Kun-Lai Summit',
  'id':86566},
{'name':'Big Bag of Herbs',
  'source':'Ashleaf Sprites or Burning Berserkers',
  'rare':False,
  'pet':False,
  'location':'The Blazing Way',
  'alternative':'',
  'id':106130},
{'name':'Overgrown Lilypad',
  'source':'Gulp Frogs',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'Sel\'ena, rare in Valley of the Four Winds',
  'id':86580},
{'name':'Hardened Shell',
  'source':'Great Turtle Furyshell or Chelon',
  'rare':False,
  'pet':False,
  'location':'West coast, former is mid-south, latter is north',
  'alternative':'Nessos the Oracle, rare in northern Kun-Lai Summit',
  'id':86584},
{'name':'Bubbling Pi\'jiu Brew',
  'source':'Spectral Windwalkers',
  'rare':False,
  'pet':False,
  'location':'Old Pi\'jiu',
  'alternative':'',
  'id':104336},
{'name':'Thick Pi\'jiu Brew',
  'source':'Spectral Brewmasters',
  'rare':False,
  'pet':False,
  'location':'Old Pi\'jiu',
  'alternative':'',
  'id':104335},
{'name':'Misty Pi\'jiu Brew',
  'source':'Spectral Mistweavers',
  'rare':False,
  'pet':False,
  'location':'Old Pi\'jiu',
  'alternative':'',
  'id':104334},
{'name':'Warning Sign',
  'source':'Jakur of Ordon',
  'rare':True,
  'pet':False,
  'location':'Firewalker Ruins',
  'alternative':'',
  'id':104331},
{'name':'Ash-Covered Horn',
  'source':'Flintlord Gairan or High Priest of Ordos',
  'rare':True,
  'pet':False,
  'location':'Ordon Sanctuary',
  'alternative':'',
  'id':104329},
{'name':'Cauterizing Core',
  'source':'Molten Guardians or Cinderfall',
  'rare':False,
  'pet':False,
  'location':'Ordon Sanctuary and the bridge just before it',
  'alternative':'',
  'id':104328},
{'name':'Captain Zvezdan\'s Lost Leg',
  'source':'Rattleskew',
  'rare':True,
  'pet':False,
  'location':'South-east of the coast, at a sunken boat',
  'alternative':'',
  'id':104321},
{'name':'Cursed Talisman',
  'source':'Spelurk',
  'rare':True,
  'pet':False,
  'location':'Cave-in event, just to the east of the court',
  'alternative':'',
  'id':104320},
{'name':'Golden Moss',
  'source':'Rock Moss',
  'rare':True,
  'pet':False,
  'location':'Cavern of Lost Souls',
  'alternative':'',
  'id':104313},
{'name':'Strange Glowing Mushroom',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Eternal Kiln',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Jadefire Spirit',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Sunset Stone',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Ashen Stone',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Blizzard Stone',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Rain Stone',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Blackflame Daggers',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Falling Flame',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Ordon Death Chime',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Blazing Sigil of Ordos',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Ordon Ceremonial Robes',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Rime of the Time-Lost Mariner',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Scuttler\'s Shell',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Partially-Digested Meal',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Swarmling of Gu\'chi',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Sticky Silkworm Goo',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Faintly-Glowing Herb',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Condensed Jademist',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Windfeather Plume',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Quivering Firestorm Egg',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Reins of the Thundering Onyx Cloud Serpent',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Pristine Stalker Hide',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Glinting Pile of Stone',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Odd Polished Stone',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Glowing Blue Ash',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Glowing Green Ash',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Bonkers',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Gulp Froglet',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Spineclaw Crab',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Skunky Alemental',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Ominous Flame',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Jademist Dancer',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Death Adder Hatchling',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Dandelion Frolicker',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Ruby Droplet',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Azure Crane Chick',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
{'name':'Ashleaf Spriteling',
  'source':'',
  'rare':False,
  'pet':False,
  'location':'',
  'alternative':'',
  'id':0},
]

class GnabbView(BrowserView):
  gnabb = gnabb
  
  def progress(self):
    _progress = self.request.get('s','')
    for i in range(0,len(_progress)):
      try:
        if int(_progress[i]):
          self.gnabb[i]['completed'] = True
        else:
          self.gnabb[i]['completed'] = False
      except IndexError: # you fucked up
        return []
    return self.gnabb
    
  def completed(self):
    return [g['id'] for g in self.gnabb if g.get('completed')]